add_newline = true

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

[username]
format = "[$user]($style)"
style_user = "bold fg:105"
show_always = true

[hostname]
format = "[@$hostname]($style) "
style = "bold fg:225"
ssh_only = false

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold purple"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"
format = "([$all_status$ahead_behind]($style) )"
conflicted = "󰞇 "
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "󰇘 "
stashed = "󰏗 "
modified = "󰷉 "
staged = "󰐖 "
renamed = "󰑕 "
deleted = "󰧧 "

[python]
symbol = " "
format = "via [$symbol$pyenv_prefix$version]($style) "

[rust]
symbol = " "

[nodejs]
symbol = "󰎙 "

[cmd_duration]
min_time = 500
format = "took [󱎫 $duration](bold yellow) "
