wallpaper {
    monitor = HDMI-A-1
    path = /usr/share/backgrounds/archlinux/sunset.jpg
    fit_mode = center
}

wallpaper {
    monitor = eDP-1
    path = /usr/share/backgrounds/archlinux/archbtw.png
    fit_mode = cover
}