# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1
windowrule {
    name = kitty-blur
    match:class = kitty
    no_blur = false
    opacity = 0.95 0.9
}

windowrule {
    name = code-no-blur
    match:class = code
    no_blur = false
    opacity = 0.95 0.9
}