##################
#### MONITORS ####
##################

# See https://wiki.hypr.land/Configuring?monitors
source = ~/.config/hypr/monitors/settings.conf

# hyprlang if INTERNAL_ENABLED
monitor = eDP-1, 1920x1080@144, 0x0, 1
# hyprlang endif
# hyprlang if !INTERNAL_ENABLED
monitor = eDP-1, disable
# hyprlang endif
